---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

## 網站資料爬取
```{r}
#這是R Code Chunk
#install.packages("rvest")
#install.packages("XML")
#install.packages("knitr")
#install.packages("rmarkdown")
library(rvest) 
pttTech1<-NULL
pttTech<-"https://www.ptt.cc/bbs/Tech_Job/index.html"
pttTechContent<-read_html(pttTech)
post_title <- pttTechContent %>% html_nodes(".title") %>% html_text()
post_NumPush<- pttTechContent %>% html_nodes(".nrec") %>% html_text()
post_author<- pttTechContent %>% html_nodes(".author") %>% html_text()
pttTech1<-data.frame(post_title,post_NumPush,post_author)
for(i in 1:10)
{
library(rvest)
post_front<- pttTechContent %>% html_nodes(".btn") %>% html_attr("href")
pttTech<-paste0("https://www.ptt.cc",post_front[4])
pttTechContent<-read_html(pttTech)
post_title <- pttTechContent %>% html_nodes(".title") %>% html_text()
post_NumPush<- pttTechContent %>% html_nodes(".nrec") %>% html_text()
post_author<- pttTechContent %>% html_nodes(".author") %>% html_text()
pttTech2<-data.frame(post_title,post_NumPush,post_author)
pttTech1<-rbind(pttTech1,pttTech2)
}
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
library(knitr)
knitr::kable(pttTech1) 
```

## 解釋爬蟲結果 
```{r}
#這是R Code Chunk
dim(pttTech1)

```
共爬出219篇文章


```{r}
#這是R Code Chunk
sort(table(pttTech1$post_author),decreasing = T)
```
哪個作者的文章數最多?
被刪除的作者文章數最多XD

```{r}

```
爬到2000多篇文章後發現作者發文最多的都是被刪除的人XD


